{{- if .Values.services.airtableGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyairtable-stack.fullname" . }}-{{ .Values.services.airtableGateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pyairtable-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.services.airtableGateway.name }}
spec:
  replicas: {{ .Values.services.airtableGateway.replicas }}
  selector:
    matchLabels:
      {{- include "pyairtable-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: airtable-gateway
  template:
    metadata:
      labels:
        {{- include "pyairtable-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: airtable-gateway
    spec:
      containers:
      - name: {{ .Values.services.airtableGateway.name }}
        image: {{ include "pyairtable-stack.image" (dict "registry" .Values.global.imageRegistry "repository" .Values.services.airtableGateway.image "tag" .Values.services.airtableGateway.tag) | quote }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.services.airtableGateway.port }}
        env:
        {{- include "pyairtable-stack.commonSecretEnvVars" . | nindent 8 }}
        {{- include "pyairtable-stack.commonConfigEnvVars" . | nindent 8 }}
        - name: AIRTABLE_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "pyairtable-stack.fullname" . }}-secrets
              key: AIRTABLE_TOKEN
        - name: AIRTABLE_BASE
          valueFrom:
            secretKeyRef:
              name: {{ include "pyairtable-stack.fullname" . }}-secrets
              key: AIRTABLE_BASE
        resources:
          {{- toYaml .Values.services.airtableGateway.resources | nindent 10 }}
        {{- if .Values.healthChecks.enabled }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.airtableGateway.port }}
          initialDelaySeconds: {{ .Values.healthChecks.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.airtableGateway.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: {{ .Values.healthChecks.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.failureThreshold }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.airtableGateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pyairtable-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.services.airtableGateway.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.airtableGateway.port }}
    targetPort: {{ .Values.services.airtableGateway.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "pyairtable-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: airtable-gateway
{{- end }}