{{- if .Values.databases.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pyairtable-stack.fullname" . }}-postgres-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pyairtable-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.databases.postgres.persistence.size }}
  {{- if .Values.databases.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.databases.postgres.persistence.storageClass }}
  {{- end }}
---
{{- end }}
{{- if .Values.databases.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pyairtable-stack.fullname" . }}-redis-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pyairtable-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.databases.redis.persistence.size }}
  {{- if .Values.databases.redis.persistence.storageClass }}
  storageClassName: {{ .Values.databases.redis.persistence.storageClass }}
  {{- end }}
---
{{- end }}
{{- if .Values.persistence.fileUploads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pyairtable-stack.fullname" . }}-file-uploads-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pyairtable-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: file-uploads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.fileUploads.size }}
  {{- if .Values.persistence.fileUploads.storageClass }}
  storageClassName: {{ .Values.persistence.fileUploads.storageClass }}
  {{- end }}
{{- end }}