apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyairtable-stack.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pyairtable-stack.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded secrets - these should be properly encoded in production
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | b64enc | quote }}
  AIRTABLE_TOKEN: {{ .Values.secrets.airtableToken | b64enc | quote }}
  AIRTABLE_BASE: {{ .Values.secrets.airtableBase | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyairtable-stack.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pyairtable-stack.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.app.environment | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  THINKING_BUDGET: {{ .Values.secrets.thinkingBudget | quote }}
  CORS_ORIGINS: {{ .Values.secrets.corsOrigins | quote }}
  MAX_FILE_SIZE: {{ .Values.secrets.maxFileSize | quote }}
  ALLOWED_EXTENSIONS: {{ .Values.secrets.allowedExtensions | quote }}
  NODE_ENV: {{ .Values.app.environment | quote }}
  REQUIRE_API_KEY: "true"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRES_IN: "24h"
  PASSWORD_MIN_LENGTH: "8"
  PASSWORD_HASH_ROUNDS: "12"
  ANALYTICS_RETENTION_DAYS: "90"
  METRICS_BATCH_SIZE: "100"
  USE_HTTP_MCP: "true"
  USE_REDIS_SESSIONS: "true"
  MCP_SERVER_MODE: "http"
  MCP_SERVER_PORT: "8001"
  DEFAULT_WORKFLOW_TIMEOUT: "300"
  MAX_WORKFLOW_RETRIES: "3"
  SCHEDULER_CHECK_INTERVAL: "30"
  UPLOAD_DIR: "/tmp/uploads"
  NEXT_PUBLIC_ENABLE_DEBUG: "false"
  NEXT_PUBLIC_SHOW_COST_TRACKING: "true"