apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: redis-cache-kill
  namespace: chaos-engineering
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "redis"
  duration: "30s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: redis-memory-pressure
  namespace: chaos-engineering
spec:
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "redis"
  stressors:
    memory:
      workers: 1
      size: "80%"
  duration: "5m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: redis-connection-delay
  namespace: chaos-engineering
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "redis"
  delay:
    latency: "2s"
    correlation: "100"
    jitter: "500ms"
  duration: "3m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: redis-disk-corruption
  namespace: chaos-engineering
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "redis"
  volumePath: "/data"
  path: "**/*.rdb"
  errno: 5  # EIO - Input/output error
  percent: 20
  duration: "1m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: cache-cluster-partition
  namespace: chaos-engineering
spec:
  action: partition
  mode: fixed
  value: "1"
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "redis"
      "role": "master"
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - pyairtable
      labelSelectors:
        "app": "redis"
        "role": "replica"
  duration: "2m"