apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: pyairtable-dev
  labels:
    app: mcp-server
    component: protocol
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
        component: protocol
        environment: development
    spec:
      containers:
      - name: mcp-server
        image: mcp-server-py:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8001
          protocol: TCP
        
        env:
        - name: PORT
          value: "8001"
        - name: HOST
          value: "0.0.0.0"
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: pyairtable-dev-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: pyairtable-dev-config
              key: LOG_LEVEL
        - name: ENABLE_DEBUG_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: pyairtable-dev-config
              key: ENABLE_DEBUG_ENDPOINTS
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: pyairtable-dev-secrets
              key: API_KEY
        - name: AIRTABLE_TOKEN
          valueFrom:
            secretKeyRef:
              name: pyairtable-dev-secrets
              key: AIRTABLE_TOKEN
        - name: AIRTABLE_GATEWAY_URL
          value: "http://airtable-gateway:8002"
        - name: MCP_SERVER_MODE
          value: "http"
        - name: MCP_SERVER_PORT
          value: "8001"
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      
      volumes:
      - name: app-logs
        emptyDir: {}
      
      terminationGracePeriodSeconds: 10
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: pyairtable-dev
  labels:
    app: mcp-server
    component: protocol
    environment: development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: mcp-server

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-external
  namespace: pyairtable-dev
  labels:
    app: mcp-server
    component: protocol-external
    environment: development
spec:
  type: NodePort
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    nodePort: 30001
    protocol: TCP
  selector:
    app: mcp-server