version: '3.8'

services:
  # Test the new Go service
  auth-service:
    build:
      context: ./go-services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - PORT=8100
    networks:
      - test-network

  # Test the new Python service  
  ai-service:
    build:
      context: ./python-services/ai-service
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - PORT=8200
    networks:
      - test-network

  # Test the new Frontend service
  auth-frontend:
    build:
      context: ./frontend-services/auth-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
