version: '3.8'

# Development override for live code reloading
services:
  api-gateway:
    build:
      context: ../pyairtable-api-gateway
      dockerfile: Dockerfile
    volumes:
      - ../pyairtable-api-gateway/src:/app/src:ro
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - LOG_LEVEL=DEBUG

  llm-orchestrator:
    build:
      context: ../llm-orchestrator-py
      dockerfile: Dockerfile
    volumes:
      - ../llm-orchestrator-py/src:/app/src:ro
      - ../mcp-server-py:/app/mcp-server:ro
    command: uvicorn src.main:app --host 0.0.0.0 --port 8003 --reload
    environment:
      - LOG_LEVEL=DEBUG

  mcp-server:
    build:
      context: ../mcp-server-py
      dockerfile: Dockerfile
    volumes:
      - ../mcp-server-py/src:/app/src:ro
    environment:
      - LOG_LEVEL=DEBUG

  airtable-gateway:
    build:
      context: ../airtable-gateway-py
      dockerfile: Dockerfile
    volumes:
      - ../airtable-gateway-py/src:/app/src:ro
    command: uvicorn src.main:app --host 0.0.0.0 --port 8002 --reload
    environment:
      - LOG_LEVEL=DEBUG