version: '3.8'

# Frontend service for full-stack development
services:
  # Frontend development server
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_KEY=${API_KEY}
      - NEXT_PUBLIC_ENVIRONMENT=development
      - NEXT_PUBLIC_ENABLE_DEVTOOLS=true
    volumes:
      - ../frontend/src:/app/src:cached
      - ../frontend/public:/app/public:cached
      - ../frontend/pages:/app/pages:cached
      - ../frontend/components:/app/components:cached
      # Exclude node_modules from volume mounting for performance
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - pyairtable-network
    restart: unless-stopped
    command: npm run dev

networks:
  pyairtable-network:
    external: true