# Logstash Configuration for PyAirtable Platform
# Optimized for performance and cost-efficiency

# Node configuration
node.name: logstash-pyairtable
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs

# Pipeline configuration
pipeline.id: pyairtable-main
pipeline.workers: 2
pipeline.batch.size: 1000
pipeline.batch.delay: 50

# Pipeline ordering (if multiple pipelines)
pipeline.ordered: auto

# Queue configuration for performance
queue.type: memory
queue.max_bytes: 1gb
queue.max_events: 100000

# Dead letter queue
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 100mb

# HTTP API for monitoring
http.host: "0.0.0.0"
http.port: 9600

# Logging configuration
log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["elasticsearch:9200"]
monitoring.elasticsearch.index: ".monitoring-logstash"

# X-Pack settings (if available)
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["elasticsearch:9200"]

# JVM settings reference
config.reload.automatic: true
config.reload.interval: 3s

# Path to pipeline configurations
path.config: /usr/share/logstash/pipeline

# Modules configuration
modules:
  - name: netflow
    var.elasticsearch.hosts: ["elasticsearch:9200"]
    var.kibana.host: "kibana:5601"

# Performance tuning
config.support_escapes: true
config.field_reference.escape_style: percent