# Loki Configuration for PyAirtable Platform
# Lightweight log aggregation with retention policies

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# === RETENTION POLICIES ===
# Cost optimization - keep logs for limited time
limits_config:
  # Global limits
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  creation_grace_period: 10m
  
  # Per-tenant limits
  ingestion_rate_mb: 4        # 4MB/s ingestion limit
  ingestion_burst_size_mb: 6  # 6MB burst
  max_line_size: 256kb        # Maximum line size
  max_concurrent_tail_requests: 10
  
  # Query limits
  max_query_length: 12000h    # 500 days max query range
  max_query_parallelism: 32
  max_query_series: 500
  max_streams_per_user: 10000
  max_line_size_truncate: true

# === COMPACTOR CONFIGURATION ===
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# === TABLE MANAGER (for retention) ===
table_manager:
  retention_deletes_enabled: true
  retention_period: 336h  # 14 days retention

# === INGESTER CONFIGURATION ===
ingester:
  max_chunk_age: 1h
  chunk_retain_period: 30s
  chunk_encoding: snappy
  
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  
  # Flush settings
  chunk_idle_period: 30s
  chunk_block_size: 262144
  max_transfer_retries: 0

# === STORAGE CONFIGURATION ===
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    resync_interval: 5s
    shared_store: filesystem
  
  filesystem:
    directory: /loki/chunks

# === CHUNK STORE CONFIGURATION ===
chunk_store_config:
  max_look_back_period: 0s

# === ANALYTICS ===
analytics:
  reporting_enabled: false