apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyairtable-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: prod
    team: platform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: https://github.com/Reg-Kris/pyairtable-compose.git
    targetRevision: main
    path: k8s/helm/pyairtable-stack
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: prod
        - name: global.imageTag
          value: main-latest
        - name: global.domain
          value: pyairtable.com
        - name: resources.requests.cpu
          value: 500m
        - name: resources.requests.memory
          value: 512Mi
        - name: resources.limits.cpu
          value: 2000m
        - name: resources.limits.memory
          value: 2Gi
        - name: replicaCount
          value: "3"
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "3"
        - name: autoscaling.maxReplicas
          value: "10"
        - name: monitoring.enabled
          value: "true"
        - name: security.podSecurityPolicy.enabled
          value: "true"
        - name: networkPolicy.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: pyairtable-prod
  syncPolicy:
    # Manual sync for production
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP