apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyairtable-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: staging
    team: platform
spec:
  project: default
  source:
    repoURL: https://github.com/Reg-Kris/pyairtable-compose.git
    targetRevision: main
    path: k8s/helm/pyairtable-stack
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: global.environment
          value: staging
        - name: global.imageTag
          value: main-latest
        - name: global.domain
          value: staging.pyairtable.com
        - name: resources.requests.cpu
          value: 200m
        - name: resources.requests.memory
          value: 256Mi
        - name: resources.limits.cpu
          value: 1000m
        - name: resources.limits.memory
          value: 1Gi
        - name: replicaCount
          value: "2"
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "2"
        - name: autoscaling.maxReplicas
          value: "5"
  destination:
    server: https://kubernetes.default.svc
    namespace: pyairtable-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP