# Workspace Service Configuration

server:
  host: "0.0.0.0"
  port: 8080
  grpc_port: 50053
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

database:
  host: "localhost"
  port: 5432
  name: "workspace_service"
  user: "postgres"
  password: ""
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  migration_path: "file://migrations"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10
  idle_timeout: "5m"

logging:
  level: "info"
  format: "json"