version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: workspace-postgres
    environment:
      POSTGRES_DB: workspace_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: workspace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  workspace-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workspace-service
    ports:
      - "50053:50053"
    environment:
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: workspace_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSLMODE: disable
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # Server
      GRPC_PORT: 50053
      
      # Logging
      LOG_LEVEL: debug
      LOG_FORMAT: json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50053"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
  redis_data: