global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@pyairtable.local'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 10s
      repeat_interval: 1h
    - match:
        alertname: ServiceDown
      receiver: 'service-down-alerts'
      group_wait: 5s
      repeat_interval: 15m

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://webhook-receiver:9093/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://webhook-receiver:9093/webhook/critical'
        send_resolved: true

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://webhook-receiver:9093/webhook/warning'
        send_resolved: true

  - name: 'service-down-alerts'
    webhook_configs:
      - url: 'http://webhook-receiver:9093/webhook/service-down'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*(High|Error|Latency).*'
    equal: ['job', 'instance']