global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pyairtable-basic'
    environment: 'development'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # PyAirtable Working Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  - job_name: 'airtable-gateway'
    static_configs:
      - targets: ['airtable-gateway:8002']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:8001']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  - job_name: 'llm-orchestrator'
    static_configs:
      - targets: ['llm-orchestrator:8003']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # Infrastructure Services
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 15s
    metrics_path: /metrics

  # Health Check Endpoints (HTTP probe)
  - job_name: 'api-gateway-health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8000/health
        - http://api-gateway:8000/ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'service-health-checks'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://airtable-gateway:8002/health
        - http://mcp-server:8001/health
        - http://llm-orchestrator:8003/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Blackbox exporter for health probes
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']
    scrape_interval: 30s

# Additional container monitoring via static discovery
  # Note: Docker service discovery removed due to configuration complexity