# PyAirtable Platform Prometheus Configuration
# Basic monitoring setup for production deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pyairtable-platform'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway (Go)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Auth Service (Go)
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # User Service (Go)
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Workspace Service (Go)
  - job_name: 'workspace-service'
    static_configs:
      - targets: ['workspace-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Airtable Gateway (Python)
  - job_name: 'airtable-gateway'
    static_configs:
      - targets: ['airtable-gateway:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MCP Server (Python)
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # LLM Orchestrator (Python)
  - job_name: 'llm-orchestrator'
    static_configs:
      - targets: ['llm-orchestrator:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Platform Services (Python)
  - job_name: 'platform-services'
    static_configs:
      - targets: ['platform-services:8007']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Automation Services (Python)
  - job_name: 'automation-services'
    static_configs:
      - targets: ['automation-services:8006']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Infrastructure monitoring
  # PostgreSQL Exporter (if deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (if deployed)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'node-exporter:9100'

  # Docker container metrics (if using cadvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s