global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pyairtable-local'
    environment: 'development'

scrape_configs:
  # Monitoring stack self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Service health monitoring using blackbox exporter
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8000/api/health
        - http://ai-processing-service:8001/health
        - http://airtable-gateway:8002/health
        - http://workspace-service:8003/health
        - http://platform-services:8007/health
        - http://automation-services:8006/health
        - http://saga-orchestrator:8008/health/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115