global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pyairtable-local'
    environment: 'development'

rule_files:
  - "alerting-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # PyAirtable Application Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  - job_name: 'ai-processing-service'
    static_configs:
      - targets: ['ai-processing-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'airtable-gateway'
    static_configs:
      - targets: ['airtable-gateway:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'workspace-service'
    static_configs:
      - targets: ['workspace-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'platform-services'
    static_configs:
      - targets: ['platform-services:8007']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'automation-services'
    static_configs:
      - targets: ['automation-services:8006']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'saga-orchestrator'
    static_configs:
      - targets: ['saga-orchestrator:8008']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'redis-streams'
    static_configs:
      - targets: ['redis-streams-exporter:9122']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'redis-queue'
    static_configs:
      - targets: ['redis-queue-exporter:9123']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Queue System Monitoring
  - job_name: 'queue-processor'
    static_configs:
      - targets: ['queue-processor:8009']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Auth Monitor Service
  - job_name: 'auth-monitor'
    static_configs:
      - targets: ['auth-monitor:8090']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Monitoring Stack Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # OTEL Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Container and Node Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'

# Remote Write Configuration for Long-term Storage
# remote_write:
#   - url: http://mimir:9009/api/v1/push
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500