apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-api-gateway
  namespace: chaos-engineering
spec:
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "api-gateway"
  stressors:
    cpu:
      workers: 2
      load: 90
  duration: "5m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-platform-services
  namespace: chaos-engineering
spec:
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "platform-services"
  stressors:
    memory:
      workers: 1
      size: "512MB"
  duration: "3m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: disk-fill-simulation
  namespace: chaos-engineering
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "automation-services"
  volumePath: "/tmp"
  path: "**/*"
  errno: 28  # ENOSPC - No space left on device
  percent: 10
  duration: "2m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: combined-resource-stress
  namespace: chaos-engineering
spec:
  mode: fixed-percent
  value: "30"
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "tier": "backend"
  stressors:
    cpu:
      workers: 1
      load: 70
    memory:
      workers: 1
      size: "256MB"
  duration: "8m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: slow-disk-reads
  namespace: chaos-engineering
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "component": "file-processor"
  volumePath: "/data"
  path: "**/*"
  delay: "500ms"
  percent: 80
  duration: "5m"