apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: api-gateway-crash
  namespace: chaos-engineering
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "api-gateway"
  duration: "30s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: auth-service-crash
  namespace: chaos-engineering
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "auth-service"
  duration: "30s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: platform-services-crash
  namespace: chaos-engineering
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "platform-services"
  duration: "30s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: automation-services-crash
  namespace: chaos-engineering
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "app": "automation-services"
  duration: "30s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: multiple-pod-failure
  namespace: chaos-engineering
spec:
  action: pod-kill
  mode: fixed-percent
  value: "25"
  selector:
    namespaces:
      - pyairtable
    labelSelectors:
      "tier": "backend"
  duration: "60s"