# AlertManager Configuration for LGTM Stack
# Optimized for ARM64 and local development

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@localhost'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-receiver'
    group_wait: 5s
    repeat_interval: 30m

receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://localhost:5001/alerts'
    send_resolved: true

- name: 'critical-receiver'
  webhook_configs:
  - url: 'http://localhost:5001/critical-alerts'
    send_resolved: true

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']