apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtable-gateway
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: airtable-gateway
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airtable-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: airtable-gateway
        app.kubernetes.io/component: gateway
    spec:
      containers:
      - name: airtable-gateway
        image: ghcr.io/reg-kris/airtable-gateway-py:latest
        ports:
        - containerPort: 8002
        env:
        - name: AIRTABLE_TOKEN
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: AIRTABLE_TOKEN
        - name: AIRTABLE_BASE
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: AIRTABLE_BASE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: API_KEY
        envFrom:
        - configMapRef:
            name: pyairtable-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: airtable-gateway-service
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: airtable-gateway
    app.kubernetes.io/component: gateway
spec:
  selector:
    app.kubernetes.io/name: airtable-gateway
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP