apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-services
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: automation-services
    app.kubernetes.io/component: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: automation-services
  template:
    metadata:
      labels:
        app.kubernetes.io/name: automation-services
        app.kubernetes.io/component: automation
    spec:
      containers:
      - name: automation-services
        image: ghcr.io/reg-kris/pyairtable-automation-services:latest
        ports:
        - containerPort: 8006
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: API_KEY
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: POSTGRES_DB
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: REDIS_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        envFrom:
        - configMapRef:
            name: pyairtable-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        volumeMounts:
        - name: file-uploads
          mountPath: /tmp/uploads
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: file-uploads
        persistentVolumeClaim:
          claimName: file-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: automation-services-service
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: automation-services
    app.kubernetes.io/component: automation
spec:
  selector:
    app.kubernetes.io/name: automation-services
  ports:
  - port: 8006
    targetPort: 8006
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploads-pvc
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: automation-services
    app.kubernetes.io/component: automation
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi