apiVersion: v1
kind: ConfigMap
metadata:
  name: pyairtable-config
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: pyairtable
    app.kubernetes.io/component: config
data:
  # Environment configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # Service URLs (internal Kubernetes)
  AIRTABLE_GATEWAY_URL: "http://airtable-gateway-service:8002"
  MCP_SERVER_URL: "http://mcp-server-service:8001"
  LLM_ORCHESTRATOR_URL: "http://llm-orchestrator-service:8003"
  PLATFORM_SERVICES_URL: "http://platform-services-service:8007"
  AUTOMATION_SERVICES_URL: "http://automation-services-service:8006"
  
  # Database URLs
  DATABASE_URL: "postgresql://customer_user:REPLACE_PASSWORD@postgres-service:5432/pyairtable_customer"
  REDIS_URL: "redis://redis-service:6379"
  
  # Security settings
  REQUIRE_API_KEY: "true"
  CORS_ORIGINS: "http://localhost:3000"
  
  # MCP Server settings
  MCP_SERVER_MODE: "http"
  MCP_SERVER_PORT: "8001"
  USE_HTTP_MCP: "true"
  USE_REDIS_SESSIONS: "true"
  
  # File processing
  MAX_FILE_SIZE: "25MB"
  ALLOWED_EXTENSIONS: "pdf,doc,docx,txt,csv,xlsx"
  UPLOAD_DIR: "/tmp/uploads"
  
  # Workflow settings
  DEFAULT_WORKFLOW_TIMEOUT: "600"
  MAX_WORKFLOW_RETRIES: "3"
  SCHEDULER_CHECK_INTERVAL: "30"
  
  # Analytics settings
  ANALYTICS_RETENTION_DAYS: "365"
  METRICS_BATCH_SIZE: "100"
  
  # Auth settings
  PASSWORD_MIN_LENGTH: "12"
  PASSWORD_HASH_ROUNDS: "12"