apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-services
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: platform-services
    app.kubernetes.io/component: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-services
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-services
        app.kubernetes.io/component: platform
    spec:
      containers:
      - name: platform-services
        image: ghcr.io/reg-kris/pyairtable-platform-services:latest
        ports:
        - containerPort: 8007
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: JWT_SECRET
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: POSTGRES_DB
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pyairtable-secrets
              key: REDIS_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        envFrom:
        - configMapRef:
            name: pyairtable-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: platform-services-service
  namespace: pyairtable-customer
  labels:
    app.kubernetes.io/name: platform-services
    app.kubernetes.io/component: platform
spec:
  selector:
    app.kubernetes.io/name: platform-services
  ports:
  - port: 8007
    targetPort: 8007
    protocol: TCP
  type: ClusterIP