name: pyairtable_sdk
description: PyAirtable SDK for Flutter applications with offline support and real-time updates
version: 1.0.0
homepage: https://github.com/pyairtable/mobile-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  http: ^1.1.0
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Local storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  
  # Network connectivity
  connectivity_plus: ^4.0.0
  
  # Background tasks
  workmanager: ^0.5.1
  
  # File operations
  path_provider: ^2.1.0
  dio: ^5.3.0
  
  # Push notifications
  flutter_local_notifications: ^15.1.0
  firebase_messaging: ^14.6.0
  
  # Utilities
  uuid: ^3.0.7
  rxdart: ^0.27.7
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pyairtable.sdk
        pluginClass: PyAirtableSdkPlugin
      ios:
        pluginClass: PyAirtableSdkPlugin