version: '3.8'

services:
  automation-domain:
    build: .
    ports:
      - "8090:8090"
    environment:
      - ENV=development
      - HOST=0.0.0.0
      - PORT=8090
      - RELOAD=true
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/pyairtable_automation
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - INTERNAL_API_KEY=dev-internal-key-123
      - JWT_SECRET_KEY=dev-jwt-secret-key-456
      - WEBHOOK_SECRET_KEY=dev-webhook-secret-789
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USE_TLS=false
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app
    command: python -m src.main
    networks:
      - automation-network

  automation-worker:
    build: .
    environment:
      - ENV=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/pyairtable_automation
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - INTERNAL_API_KEY=dev-internal-key-123
      - JWT_SECRET_KEY=dev-jwt-secret-key-456
      - WEBHOOK_SECRET_KEY=dev-webhook-secret-789
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USE_TLS=false
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app
    command: celery -A src.workers.celery_app worker --loglevel=info --queues=critical,workflow,notification,webhook,automation,default --concurrency=4
    networks:
      - automation-network

  automation-beat:
    build: .
    environment:
      - ENV=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/pyairtable_automation
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - INTERNAL_API_KEY=dev-internal-key-123
      - JWT_SECRET_KEY=dev-jwt-secret-key-456
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: celery -A src.workers.celery_app beat --loglevel=info
    networks:
      - automation-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pyairtable_automation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - automation-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - automation-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - automation-network

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - FLOWER_PORT=5555
    depends_on:
      - redis
    command: celery -A src.workers.celery_app flower --port=5555
    networks:
      - automation-network

volumes:
  postgres_data:
  redis_data:

networks:
  automation-network:
    driver: bridge