# Grafana Datasources Configuration
apiVersion: 1

datasources:
  # Prometheus - Metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
    version: 1

  # Jaeger - Distributed Tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-all-in-one:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'elasticsearch'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags: [
          { key: 'service.name', value: 'service' },
          { key: 'span.kind', value: 'span_kind' }
        ]
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: 'trace_id:"$${__trace.traceID}"'
    version: 1

  # Elasticsearch - Logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logstash-*"
    editable: true
    jsonData:
      index: "logstash-*"
      timeField: "@timestamp"
      esVersion: "8.11.0"
      includeFrozen: false
      logMessageField: "message"
      logLevelField: "level"
      maxConcurrentShardRequests: 5
    version: 1

  # Loki - Lightweight log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: 'jaeger'
          matcherRegex: 'trace_id=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'
      alertmanager:
        handleGrafanaManagedAlerts: true
        implementation: prometheus
    version: 1