# Automation Services Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-services
  namespace: pyairtable-production
  labels:
    app: automation-services
    component: automation
    tier: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: automation-services
  template:
    metadata:
      labels:
        app: automation-services
        component: automation
        tier: backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8006"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: pyairtable-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: automation-services
        image: ghcr.io/reg-kris/pyairtable-automation-services:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8006
          name: http
          protocol: TCP
        env:
        # Service Configuration
        - name: PORT
          value: "8006"
        - name: MCP_SERVER_URL
          value: "http://mcp-server:8001"
        - name: PLATFORM_SERVICES_URL
          value: "http://platform-services:8007"
        envFrom:
        - secretRef:
            name: pyairtable-api-keys
        - secretRef:
            name: pyairtable-app-config
        - secretRef:
            name: pyairtable-database
        - secretRef:
            name: pyairtable-redis
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: file-uploads
          mountPath: /tmp/uploads
      volumes:
      - name: file-uploads
        persistentVolumeClaim:
          claimName: automation-services-pvc
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - automation-services
              topologyKey: kubernetes.io/hostname
---
# Persistent Volume Claim for file uploads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-services-pvc
  namespace: pyairtable-production
  labels:
    app: automation-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: automation-services
  namespace: pyairtable-production
  labels:
    app: automation-services
    component: automation
spec:
  type: ClusterIP
  ports:
  - port: 8006
    targetPort: 8006
    protocol: TCP
    name: http
  selector:
    app: automation-services
---
# HorizontalPodAutoscaler for Automation Services
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: automation-services-hpa
  namespace: pyairtable-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: automation-services
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60