# SAGA Orchestrator Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-orchestrator
  namespace: pyairtable-production
  labels:
    app: saga-orchestrator
    component: orchestrator
    tier: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saga-orchestrator
  template:
    metadata:
      labels:
        app: saga-orchestrator
        component: orchestrator
        tier: backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8008"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: pyairtable-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: saga-orchestrator
        image: ghcr.io/reg-kris/pyairtable-saga-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8008
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        # Service Configuration
        - name: PORT
          value: "8008"
        - name: REQUIRE_API_KEY
          value: "true"
        - name: USE_REDIS_EVENT_BUS
          value: "true"
        - name: METRICS_PORT
          value: "9090"
        # Service URLs for SAGA steps
        - name: AUTH_SERVICE_URL
          value: "http://platform-services:8007"
        - name: USER_SERVICE_URL
          value: "http://platform-services:8007"
        - name: PERMISSION_SERVICE_URL
          value: "http://platform-services:8007"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://automation-services:8006"
        - name: AIRTABLE_CONNECTOR_URL
          value: "http://airtable-gateway:8002"
        - name: SCHEMA_SERVICE_URL
          value: "http://platform-services:8007"
        - name: WEBHOOK_SERVICE_URL
          value: "http://automation-services:8006"
        - name: DATA_SYNC_SERVICE_URL
          value: "http://automation-services:8006"
        envFrom:
        - secretRef:
            name: pyairtable-api-keys
        - secretRef:
            name: pyairtable-app-config
        - secretRef:
            name: pyairtable-database
        - secretRef:
            name: pyairtable-redis
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 40
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - saga-orchestrator
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator
  namespace: pyairtable-production
  labels:
    app: saga-orchestrator
    component: orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 8008
    targetPort: 8008
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: saga-orchestrator
---
# HorizontalPodAutoscaler for SAGA Orchestrator
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saga-orchestrator-hpa
  namespace: pyairtable-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saga-orchestrator
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60