version: '3.8'

services:
  chat-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:7000
      - VITE_WS_BASE_URL=ws://localhost:7000
    depends_on:
      - api-gateway
    networks:
      - pyairtable-network

networks:
  pyairtable-network:
    external: true