name: pyairtable_flutter_example
description: A comprehensive example app demonstrating PyAirtable Flutter SDK
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # PyAirtable SDK
  pyairtable_sdk:
    path: ../../flutter-sdk
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.0
  
  # Navigation
  go_router: ^10.0.0
  
  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  
  # File Operations
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  
  # UI Helpers
  flutter_spinkit: ^5.2.0
  lottie: ^2.6.0
  cached_network_image: ^3.3.0
  
  # Utils
  intl: ^0.18.1
  path_provider: ^2.1.1
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700